- hosts: my
  remote_user: igorek
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub 
  tasks:
    - name: Установка Nginx
      apt:
        name: nginx
        state: present
      become: yes

    - name: Запуск Nginx
      service:
        name: nginx
        state: started
      become: yes